/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ServicesRouteImport } from './routes/services'
import { Route as GoblinWayRouteImport } from './routes/goblin-way'
import { Route as EverlenRouteImport } from './routes/everlen'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as BookatoonRouteImport } from './routes/bookatoon'
import { Route as IndexRouteImport } from './routes/index'

const ServicesRoute = ServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => rootRouteImport,
} as any)
const GoblinWayRoute = GoblinWayRouteImport.update({
  id: '/goblin-way',
  path: '/goblin-way',
  getParentRoute: () => rootRouteImport,
} as any)
const EverlenRoute = EverlenRouteImport.update({
  id: '/everlen',
  path: '/everlen',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const BookatoonRoute = BookatoonRouteImport.update({
  id: '/bookatoon',
  path: '/bookatoon',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/bookatoon': typeof BookatoonRoute
  '/contact': typeof ContactRoute
  '/everlen': typeof EverlenRoute
  '/goblin-way': typeof GoblinWayRoute
  '/services': typeof ServicesRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/bookatoon': typeof BookatoonRoute
  '/contact': typeof ContactRoute
  '/everlen': typeof EverlenRoute
  '/goblin-way': typeof GoblinWayRoute
  '/services': typeof ServicesRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/bookatoon': typeof BookatoonRoute
  '/contact': typeof ContactRoute
  '/everlen': typeof EverlenRoute
  '/goblin-way': typeof GoblinWayRoute
  '/services': typeof ServicesRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/bookatoon'
    | '/contact'
    | '/everlen'
    | '/goblin-way'
    | '/services'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/bookatoon' | '/contact' | '/everlen' | '/goblin-way' | '/services'
  id:
    | '__root__'
    | '/'
    | '/bookatoon'
    | '/contact'
    | '/everlen'
    | '/goblin-way'
    | '/services'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BookatoonRoute: typeof BookatoonRoute
  ContactRoute: typeof ContactRoute
  EverlenRoute: typeof EverlenRoute
  GoblinWayRoute: typeof GoblinWayRoute
  ServicesRoute: typeof ServicesRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/services': {
      id: '/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof ServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/goblin-way': {
      id: '/goblin-way'
      path: '/goblin-way'
      fullPath: '/goblin-way'
      preLoaderRoute: typeof GoblinWayRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/everlen': {
      id: '/everlen'
      path: '/everlen'
      fullPath: '/everlen'
      preLoaderRoute: typeof EverlenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bookatoon': {
      id: '/bookatoon'
      path: '/bookatoon'
      fullPath: '/bookatoon'
      preLoaderRoute: typeof BookatoonRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BookatoonRoute: BookatoonRoute,
  ContactRoute: ContactRoute,
  EverlenRoute: EverlenRoute,
  GoblinWayRoute: GoblinWayRoute,
  ServicesRoute: ServicesRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
